### ISSUE TITLE
PMD ruleset does not run on latest PMD plugins

### ISSUE THREAD

**Issue by Prakash-Rabo** [jborgers/PMD-jPinpoint-rules#367] opened 2024-10-17 10:19 UTC
The PMD ruleset 6 is not compatible with the latest IntelliJ PMD plugin 2.0. Consider upgrading the ruleset to 7.

<img width="607" alt="image" src="https://github.com/user-attachments/assets/cc0c71c1-7150-43d3-8ccc-0b6415459276">

**Comment by jborgers** [comment] 2024-10-17 11:23
Duplicate of #309

**Closed by jborgers** 2024-10-17 11:23 UTC
